n = float(input('Digite o valor a ser calculado: '))
print('A tabuada de {} \n0x{}={} \n1x{}={} \n2x{}={}'.format(n,n,n*0,n,n*1,n,n*2))
print('3x{}={} \n4x{}={} \n5x{}={}'.format(n,n*3,n,n*4,n,n*5))
print('6x{}={} \n7x{}={} \n8x{}={}'.format(n,n*6,n,n*7,n,n*8))
print('9x{}={} \n10x{}={} '.format(n,n*9,n,n*10,))
